spring:
  profiles:
    active: cloud
---
spring:
  profiles: cloud
  jpa:
    show_sql: false
eureka:
  client:
    serviceUrl:
      #defaultZone: http://discovery-ps.cfapps.io/eureka/
      defaultZone: ${vcap.services.discovery.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
    hostname: product-ps.cfapps.io
    nonSecurePort: 80
#ribbon:
#  eureka:
#    enabled: true
---
spring:
  profiles: development
  jpa:
    show_sql: false
configuration:
  newValue: some value
endpoints:
  restart:
    enabled: true
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery.credentials.uri:http://127.0.0.1:8761}/eureka/
      #defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    #hostname: product-ps.cfapps.io
    #nonSecurePort: 80
#ribbon:
#  eureka:
#    enabled: true
